import { NavigatorScreenParams } from "@react-navigation/native";
import { BottomTabParamList } from "./BottomTabParamList";

export type RootStackParamList = {
    DrawerNavigation: NavigatorScreenParams<BottomTabParamList>;
    Damo: undefined;
    splash: undefined;
    ChooseLanguage:{ data?: any };
    SignUp: undefined;
    SignIn: undefined;
    Onbording: undefined;
    ComplateProfile: undefined;
    Login: undefined;
    Register: undefined;
    Forgot: undefined;
    Otp: undefined;
    NewPassword: undefined;
    ChangePassword: undefined;
    Settings: undefined;
    Comments: undefined;
    homescreen: undefined;
    createpost: undefined;
    notification: undefined;
    status: undefined;
    like: undefined;
    BottomNavigation: undefined;
    SingleChat:undefined;
    AddStory: undefined;
    Video: undefined;
    NewChat: undefined;
    Followers: undefined;
    Search: undefined;
    SettingNotification: undefined;
    Security: undefined;
    LoginActivity: undefined;
    SavedLogin: undefined;
    Towfactor: undefined;
    Account: undefined;
    PersonalInformation: undefined;
    Contacts: undefined;
    About: undefined;
    PrivacyPolicy: undefined;
    Terms: undefined;
    Theme: undefined;
    Profile: undefined;
    EditProfile: undefined;
    Language: { data?: any };
    Suggestions: undefined;
    ProfilePost: undefined;
    ProfileReels: undefined;
    AnotherProfile: undefined;
    JobDetails:{ data?: any };
    Save: undefined;
    Savepost: undefined;
    SaveReels: undefined;
    ActionSheet: undefined;
    JobApplied: undefined;
    AboutCompany: { data?: any }; 
    AboutGalary: undefined;
    Components: undefined;
    Coupons: undefined;
    SavedAddresses: undefined;
    Checkout: undefined;
    Addcard: undefined;
    Payment: undefined;
    SaveAddress: undefined;
    Myorder: undefined;
    Chat: undefined;
    MyApplication: undefined;
    MyApplicationStatus: { data?: any };
    ContactUs: { data?: any };
    AddCard: undefined;
    Notification: undefined;
    Home: undefined;
    Accordion: undefined;
    ActionModals: undefined;
    BottomSheet: undefined;
    ModalBox: undefined;
    Buttons: undefined;
    Badges: undefined;
    Search2: undefined;
    Charts: undefined;
    Headers: undefined;
    lists: undefined;
    Pricings: undefined;
    DividerElements: undefined;
    Snackbars: undefined;
    Socials: undefined;
    Swipeable: undefined;
    Tabs: undefined;
    Tables: undefined;
    Toggles: undefined;
    Inputs: undefined;
    Footers: undefined;
    TabStyle1: undefined;
    TabStyle2: undefined;
    TabStyle3: undefined;
    TabStyle4: undefined;
    Datepicker: undefined;
    Nextpage: undefined;
    Music: undefined;
    WriteCaption: undefined;
    CreateStory: undefined;
    Music2: undefined;
    AllSong: undefined;
    SavedMusic: undefined;
    Call: undefined;
    Reels: undefined;
};